dist: trusty
sudo: required
notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
rvm:
  - 2.1
  - 2.2
  - 2.3.7
  - 2.4.4
  - 2.5.1
# env:
#   - GROONGA_MASTER=yes
# matrix:
#   allow_failures:
#     - rvm: ruby-head
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - |
    if [ "${GROONGA_MASTER}" != "yes" ]; then
      sudo apt-get -qq -y install groonga-tokenizer-mecab
    fi
  - gem update bundler
