sudo: required
notifications:
  webhooks:
    - https://webhook.commit-email.info/
rvm:
  - 2.4
  - 2.5
  - 2.6
# env:
#   - GROONGA_MASTER=yes
# matrix:
#   allow_failures:
#     - rvm: ruby-head
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - |
    if [ "${GROONGA_MASTER}" != "yes" ]; then
      sudo apt-get -qq -y install groonga-tokenizer-mecab
    fi
  - gem update bundler
