notifications:
  email:
    recipients:
      - groonga-commit@lists.sourceforge.jp
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
# env:
#   - GROONGA_MASTER=yes
# matrix:
#   allow_failures:
#     - rvm: 2.1.0
before_install:
  - curl --silent --location https://github.com/groonga/groonga/raw/master/data/travis/setup.sh | sh
  - [ "${GROONGA_MASTER}" != "yes" ] && sudo apt-get -qq -y install groonga-tokenizer-mecab
