version: "{build}"
clone_depth: 10

notifications:
  - provider: Webhook
    url: https://webhook.commit-email.info/

image: Visual Studio 2017

environment:
  matrix:
    - ruby_version: "24"
    - ruby_version: "24-x64"
    - ruby_version: "25"
    - ruby_version: "25-x64"
    - ruby_version: "26"
    - ruby_version: "26-x64"
    - ruby_version: "27"
    - ruby_version: "27-x64"

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - ridk exec pacman -Syu --noconfirm
  - bundle install

test_script:
  - ridk exec bundle exec rake
